### ISSUE TITLE
Review a video: Basic Calculator

### ISSUE THREAD

**Issue by rodislav** [rodislav/Mister_JavaBean_Lessons#23]
please review the video here: https://docs.google.com/document/d/1Vu-EXPQXoL7Qljh8mAEcsXK5HOG-tS2mizUrq21H0wQ/edit#heading=h.5y6wu3xs5sp5

**Comment by andreicoval** [comment]
- In class Input is used the "Scanner" class for the 1st time in this tutorial. I suggest to add in documentation file a short description on it, its parameteres and the built-in methods used;
- Even if it's intuitive, the therm "package" wasn't previously described in Fundamentals or Junior documentation. I suggest to add this topic to Junior level;
- Exception Handling wasn't treated up to this stage. I suggest to add a comment in the source file;

Need to comment below to youtube video: In order to see the best quality video please click on:
Settings/Quality and choose 1080p (HD). This helps to better see the entered text, in particular the Run/Debug results, which is much more smaller than Editor text!
Also, the color of entered values (operand1, operation, operand2) in Run is not well visible. I checked on my laptop, I guess on a big screen could be better, but I suggest to find better collors anyway.
I think is better to have displayed:
1. operand1
2. operation
3. operand2
This replicates the real calculator we get used. Don't you think so?...
An interesting fact is the code itself took aprox 11 min. If you'll continue doing few other applications in the same way, with a deliverable file, than we will get use and for future applications you can just send the link on how to create the deliverable file. This way you'll save 4-5 min of your videos...significantly better in terms of video time.

Overall it's a very good material from my point of view as it replicates the way it looks in real-life production. Even the changes you made from time to time inside the classes, moving some code from a class to another, or changing some code to other form, could be tricky only from the beggining.

**Comment by rodislav** [comment]
amazing review thanks, let's make tasks out of it

**Comment by rodislav** [comment]
hm... technically, I think we;ll make it cleaner, I'll add a task to fix issues with existing video, and I'll upload new version

**Comment by rodislav** [comment]
I've made those tasks out of your comments:
#28 
#27 
#26 
#25 
#24

**Comment by rodislav** [comment]
@andreicoval could you please review the tasks I've created from your comments ?
and if there are changes needed just edit the description
