### ISSUE TITLE
Review - Video for Variables

### ISSUE THREAD

**Issue by rodislav** [rodislav/Mister_JavaBean_Lessons#7]

**Comment by andreicoval** [comment]
test message

**Comment by rodislav** [comment]
Here is the link to the video in youtube
https://www.youtube.com/watch?v=1Ao2pZCpnCw&index=3&list=PLPkoWZmDIKwCvNeBpZMejx8gQhglUxw-w

**Comment by andreicoval** [comment]
Comments:
2m50s: the text from "stackoverflow.com" is not fully visible;
5m01s: comment from row 35 is ambiguous, because in row 6 you specified that Object is also "type"

- Mouse highlight doesn't look good, when you click on some button ;
- At the end of the code, I would suggest an enumeration of few primitive data type: int, double, char...

**Comment by rodislav** [comment]
for the mouse highlight: yeah.. this is the best solution I've found so far, but I'll search more

**Comment by rodislav** [comment]
the stackoverflow post can be accessed via the link from the comment in the source code, 
so for now there is a backup solution (still, this is not best solution..)

we'll do more variables in the Junior level, still, the primitives are not very often used in production env.
they are more for frameworks
